#!/bin/sh
#
#           create installation directory
mkdir /Applications/jreality
#
#           copy distribution files to installation directory
rm    /Applications/jreality/jreality-mac-v0.2.zip
cp    jreality-mac-v0.2.zip  /Applications/jreality
#
#           unpack distribution files in installation directory
cd    /Applications/jreality
unzip xzf jreality-mac-v0.2.zip
#
#           run the program
./creator

